Update GitHub workflows

diff --git a/.github/workflows/c-cpp-build.yml b/.github/workflows/c-cpp-build.yml
--- a/.github/workflows/c-cpp-build.yml
+++ b/.github/workflows/c-cpp-build.yml
@@ -40,8 +40,11 @@ jobs:
       - name: Configure and build
         run: |
           [ -x ./autogen.sh ] && ./autogen.sh
-          ./configure
-          make
+          [ -x ./configure ] && ./configure
+          [ -s Makefile ] && make || {
+            echo "I couldn't find an autogen.sh, configure, or Makefile."
+            echo "Please check your files."
+          }
       - name: Get properties from configure.ac
         id: props
         # yamllint disable rule:line-length
@@ -96,8 +99,11 @@ jobs:
       - name: Configure and build
         run: |
           [ -x ./autogen.sh ] && ./autogen.sh
-          ./configure
-          make
+          [ -x ./configure ] && ./configure
+          [ -s Makefile ] && make || {
+            echo "I couldn't find an autogen.sh, configure, or Makefile."
+            echo "Please check your files."
+          }
       - name: Get properties from configure.ac
         id: props
         # yamllint disable rule:line-length
@@ -131,7 +137,7 @@ jobs:
           mkdir -p dist
           mv "${bin}" dist/"${safe_name}-${safe_version}-macos.tar.gz"
   c-cpp-windows-build:
-    runs-on: windows-2022
+    runs-on: windows-2025
     steps:
       - name: Checkout code
         uses: actions/checkout@v5
@@ -147,9 +153,12 @@ jobs:
         shell: cmd
       - name: Configure and build
         run: |
-          ./autogen.sh
-          ./configure
-          make
+          [ -x ./autogen.sh ] && ./autogen.sh
+          [ -x ./configure ] && ./configure
+          [ -s Makefile ] && make || {
+            echo "I couldn't find an autogen.sh, configure, or Makefile."
+            echo "Please check your files."
+          }
       - name: Get properties from configure.ac
         id: props
         # yamllint disable rule:line-length
diff --git a/.github/workflows/c-cpp-release.yml b/.github/workflows/c-cpp-release.yml
--- a/.github/workflows/c-cpp-release.yml
+++ b/.github/workflows/c-cpp-release.yml
@@ -29,8 +29,11 @@ jobs:
       - name: Configure and build
         run: |
           [ -x ./autogen.sh ] && ./autogen.sh
-          ./configure
-          make
+          [ -x ./configure ] && ./configure
+          [ -s Makefile ] && make || {
+            echo "I couldn't find an autogen.sh, configure, or Makefile."
+            echo "Please check your files."
+          }
       - name: Get properties from configure.ac
         id: props
         # yamllint disable rule:line-length
@@ -85,8 +88,11 @@ jobs:
       - name: Configure and build
         run: |
           [ -x ./autogen.sh ] && ./autogen.sh
-          ./configure
-          make
+          [ -x ./configure ] && ./configure
+          [ -s Makefile ] && make || {
+            echo "I couldn't find an autogen.sh, configure, or Makefile."
+            echo "Please check your files."
+          }
       - name: Get properties from configure.ac
         id: props
         # yamllint disable rule:line-length
@@ -126,12 +132,12 @@ jobs:
       contents: write
     steps:
       - name: Download Linux artifacts
-        uses: actions/download-artifact@v4
+        uses: actions/download-artifact@v5
         with:
           name: linux-dist
           path: dist
       - name: Download macOS artifacts
-        uses: actions/download-artifact@v4
+        uses: actions/download-artifact@v5
         with:
           name: macos-dist
           path: dist
